# Generated by Django 5.2.8 on 2025-11-10 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '__first__'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'semester', 'created_at'), name='unique_current_mark', violation_error_message='Student already has mark for this day in this subject'),
        ),
    ]
