# Generated by Django 5.2.8 on 2025-11-14 20:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('grades', '0002_alter_mark_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mark',
            name='unique_current_mark',
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 20, 23, 56, 383381, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'semester', 'mark_date'), name='unique_current_mark', violation_error_message='Student already has mark for this day in this subject'),
        ),
    ]
