# Generated by Django 5.2.8 on 2025-11-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_remove_mark_unique_current_mark_mark_mark_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark_date',
            field=models.DateField(),
        ),
    ]
