# Generated by Django 5.2.8 on 2025-11-15 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_alter_mark_mark_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
